# Generated by Django 4.0.2 on 2022-02-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
