# Generated by Django 4.0.2 on 2022-02-10 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Profile',
        ),
    ]
