# Generated by Django 4.0.2 on 2022-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
