# Generated by Django 4.0.2 on 2022-02-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
