# Generated by Django 4.0.2 on 2022-02-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='upload/userprofile.png', null=True, upload_to='upload/'),
        ),
    ]
