# Generated by Django 4.0.2 on 2022-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='G:/Shahid-Assessment/todo/static/images/upload/userprofile.png', null=True, upload_to='upload/'),
        ),
    ]
